### ISSUE TITLE
Document how to configure deis and git clients

### ISSUE THREAD

**Issue by arschles** [deis/workflow#102]
There should be a document that outlines how to configure the `deis` and `git` clients for at least the following Deis installation kinds:

1. When Deis is `helm install`ed onto a k8s cluster running on a load balancer capable cloud provider
2. When Deis is `helm install`ed onto a k8s cluster running on infrastructure where external load balancer creation is a no-op (e.g. bare metal or virtualbox)
3. When only workflow and builder are running (this will require app creation against the workflow cluster IP, then setting up a git remote directly to the builder cluster IP)

This issue follows from https://github.com/deis/router/issues/58.

**Comment by bacongobbler** [comment]
I can tackle this :)

**Comment by arschles** [comment]
:100: @bacongobbler

**Comment by krancour** [comment]
Two things...

I'm a little confused by this issue.  What "configuration" is required for the deis and git clients?  Are we talking about how a user makes the determination of what URL to use with `deis login`?

If so, isn't the answer _always_ `deis.<platform domain>`.  And _how_ that's all set up for the various scenarios you mentioned is already documented pretty extensively in the installation docs.  Maybe all we need here is a link to that?

Second thing, I'm going to mark this as a showstopper only because I think @technosophos had expressed the other day that any doc issues that would make getting started with v2 alpha challenging should be treated as such.

**Comment by bacongobbler** [comment]
Yes, the answer is to set up /etc/hosts to point to the minion nodes at deis.example.com and use `deis register deis.example.com`. We already have that doc now so we can just link to it... Or just say it's in the quickstart docs and close this out.
