### ISSUE TITLE
Edgecases for secrets and outside storage

### ISSUE THREAD

**Issue by smothiki** [deis/workflow#140]
Right now secrets are must to run buildpack type apps. we are mounting secrets to workflow in deis namespace and reading secrets from file and recreating secrets in app namespace . This is not good if the secrets change. we have to read secrets from api server and recreate the secrets in app name space.

Also when there is a new release for an existing app need to create new secret if there is a change in secrets

**Comment by bacongobbler** [comment]
This is also a bit of a security concern by mounting the platform's access and secret keys into the user's container. We should probably step back and rethink this process a bit.

**Comment by arschles** [comment]
I have an incomplete but maybe promising solution - S3's API includes the ability the generate [presigned URLs](http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html). Minio also supports them.

The tl;dr of these URLs is that they allow anyone who has one to download a pre-specified object w/o creds, within a duration after which the URL expires. If we go this route we'd obviously have to build in some kind of renewal process.

**Comment by arschles** [comment]
Actually, if each slugrunner only has to download the slug once on startup then pre-signed URLs would work fine. Is that assumption right?

**Comment by jchauncey** [comment]
ok what are the secretes and what do we use them for?

**Comment by krancour** [comment]
I believe they're used for slugrunners to fetch slugs from minio.  Buuut... this is going to be an issue all over again when we look to add end-to-end SSL.

**Comment by smothiki** [comment]
No. It's about the logic how we handle cases. Let's say user has set outside storage and deployed secrets for minio which are not meant for outside storage . We will check the URL and then minio secret mounts and follow that condition try to add minio host configuration for outside storage using minio secretes. Which would fail

**Comment by arschles** [comment]
@krancour regarding SSL, let's keep that to a separate conversation. I've heard some ideas about setting up an intermediate CA, which would change the conversation.

@smothiki that's why I suggested pre-signed URLs. _If_ the condition I listed above holds, then slugrunner would not have to mount the secret and this would become a non-issue. Otherwise, it may be worth our time to investigate a renewal protocol so that we wouldn't have to transport secrets across namespaces.

**Comment by smothiki** [comment]
I'm ok with it . If it solves the issue

**Comment by technosophos** [comment]
Okay, this issue is _way_ too generic. You need to elaborate all of the secrets that we're talking about here.

AFAIK, the only secret that we have to copy into the app namespace is the login credentials for whatever S3 storage the Slug Runner needs to use to fetch an image. We should solve that issue directly.

There are other secrets that will be passed into the Slugrunner in the future (like database connection info). But these secrets are not simply copied from outside controller to inside controller.

**Comment by technosophos** [comment]
@arschles does RiakCS support them? If not, I'm hesitant to go down that path.

**Comment by technosophos** [comment]
Other solutions:
- create a token per app
- give slugrunner read-only access to all the built slugs

**Comment by arschles** [comment]
yes, see http://docs.basho.com/riakcs/latest/cookbooks/Authentication/#S3-Authentication, under "Query String Authentication."

**Comment by technosophos** [comment]
In that case, @arschles, that'd be my preferred path.

**Comment by arschles** [comment]
see https://github.com/deis/workflow/issues/182 for continuing discussion

**Comment by krancour** [comment]
Should this be closed now that the discussion has moved to #182?

**Comment by arschles** [comment]
yes, I believe so. @smothiki please reopen if you disagree with closing this
