### ISSUE TITLE
Proposal: port boot script to go

### ISSUE THREAD

**Issue by krancour** [deis/workflow#16]

**Comment by bacongobbler** [comment]
Hmm, instead of introducing another language... I wonder if it'd be more beneficial to write the boot script in python, much like [other projects](https://github.com/docker/docker-registry/blob/master/docker_registry/run.py).

**Comment by arschles** [comment]
our prototype repo [spells out](https://github.com/deis/prototype-repo/blob/master/boot.go#L6-L11) when to use Go and when to not. any reason not to go with that?

**Comment by bacongobbler** [comment]
The prototype repo is targeted towards newer projects in a Kubernetes world, but it's also very opinionated around new projects written in Go. It misses out on other languages like Python, which the controller is written in. The only technical reasons I can come up with is the following:

 - the entire project is already written in Python, so why bother introducing another language for the sake of using Go
 - no requirement of two language build toolchains to bring up deis/workflow
 - better tie-ins with the Django Management system, South, Gunicorn, etc.
 - /bin/boot can share code/libraries with the API server rather than just shell out to /bin/sh

**Comment by arschles** [comment]
I see. that fundamental difference makes sense to me as a valid reason to stick with python.

one day I'd like to see this whole thing as a go service... ;)

**Comment by krancour** [comment]
fwiw, this issue was copied over from v1, where there had been a goal of replacing shell boot scripts with go.  It probably does make more sense to use Python in this case.

**Comment by helgi** [comment]
Doubt there are any real benefits in porting this script to `go`. Look at https://github.com/helgi/workflow/blob/remove_etcd/rootfs/bin/boot for the `boot` script looks like sans `etcd`, but still has `confd` - `< 60` lines, including comments

I'm a hard no unless it can be done in *fewer* lines in `go` / `python` or people can explain what makes it better in `go` / `python` :)

![no](http://www.reactiongifs.us/wp-content/uploads/2015/07/hahaha_no_transformers.gif)
