### ISSUE TITLE
Add documentation on specifying the correct S3 bucket

### ISSUE THREAD

**Issue by arschles** [deis/workflow#264]
When you configure your object storage configuration to do S3, you have to specify a region, but there's no easy way that I know of to figure out what that region is from the S3 UI. You can, however, find it from the `s3cmd` CLI, using `s3cmd info s3://$BUCKET_NAME`

This issue is for adding instructions on how to do so to the object storage config documentation. The instructions need not be specifically for how to do it with `s3cmd`, but they should include at least one way to see the bucket region information.

**Comment by bacongobbler** [comment]
Considering that buckets are created on-the-fly and are created in the region the user requests (default: us-east-1 as per AWS's rules) this should not be much of an issue nowadays. Either the user already knows what region the buckets were created in when they provisioned them before deploying Workflow, OR they specify it in values.yaml and it's created in the specified region.

Either way I think we've solved this issue by proxy because users don't need to manually create the buckets. That and users haven't reported any troubles in this regard for the last 11 months so I think we're safe. Feel free to re-open if this does become an issue though! :)
