### ISSUE TITLE
Update repository READMEs and remove beta references!

### ISSUE THREAD

**Issue by slack** [deis/workflow#285]
We're close! Let's pull out beta references in all project repositories.

**Comment by vdice** [comment]
@slack : In going through the project repos and removing `beta` references, I realized maybe instead of doing a wholesale removal of the standard block that most repos have:
```
-## Beta Status		
 -		
 -This Deis component is currently in beta status, and we welcome your input! If you have feedback,		
 -please [submit an issue][issues]. If you'd like to participate in development, please read the		
 -"Development" section below and [submit a pull request][prs].		
 -
```
We'd perhaps wish to keep the following in some form/fashion: 
```
...we welcome your input! If you have feedback,	
please [submit an issue][issues]. If you'd like to participate in development, please read the
"Development" section below and [submit a pull request][prs].
```
Wondering if we can get a default/standard replacement for this general case?

**Comment by helgi** [comment]
See what I did in https://github.com/deis/controller/pull/782

**Comment by vdice** [comment]
:boom: thank you @helgi, I'll go with the approach in the controller PR supplied...

**Comment by vdice** [comment]
The appropriate changes have been made in all project repositories; closing.
