### ISSUE TITLE
Missing secret creation in manifests

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#295]
`deis-workflow-rc.yaml` uses `builder-key-auth` and `django-secret-key` secrets but those files doesn't exist in this repo. 
The templates to the required files are located in [deis/charts](https://github.com/deis/charts/tree/master/deis-dev/tpl)

**Comment by bacongobbler** [comment]
We just had a discussion about maintaining the manifests in two separate places earlier today; from the conversation it sounds like we're just going to remove the manifests from each chart repository and rely solely on deis/charts for installing/testing the components during pre-stable 2.0.

**Comment by helgi** [comment]
It was kept out of the repo since we didn't want to add a `helm` dependency per se - I could add in the secrets with a static values in them just for the purpose of being able to spin it up from the repo manifests.

@bacongobbler is right tho and this may change shortly. May wait for that to see which direction we end up with.

**Comment by helgi** [comment]
Going to close this one since we are going to remove these manifests anyway
