### ISSUE TITLE
Handle dockerfiles w/o http on port 80 as internal backend services

### ISSUE THREAD

**Issue by borg286** [deis/workflow#337]
Currently Deis can consume a Dockerfile and expects only 1 port, and talk http for passthrough and monitoring on your edge routers.

> The Dockerfile must use the EXPOSE directive to expose exactly one port.
> That port must be listening for an HTTP connection.

I'd like to use Deis to create backend services, that use grpc as a protocol (which would translate to tcp in the service section of the yaml file Deis creates).
I realize that making assumptions about which port is supposed to answer http traffic, or if the resultant service should have external access.
One way to accomplish this would be to have each application defined using a Dockerfile that wants to handle http traffic that the Dockerfile expose at least port 80. If it doesn't expose port 80 then it is assumed to be internal only.
It is only slightly more arbitrary than the current rules, allows for more use cases, and is for most intents and purposes backward compatible.

**Comment by bacongobbler** [comment]
hey @borg286, I actually managed to fix this via `deis routing` which will be out for v2.4.0. I've written a blog post for this new feature, and since internal communication is all DNS, grpc, tcp, udp etc. is all usable internally. We're still unable to support other protocols than http through the router, but at least apps are able to communicate to each other using their protocol of choice now. :)

I'll close this issue once the blog post is published to deis.com/blog.

**Comment by bacongobbler** [comment]
https://deis.com/blog/2016/private-applications-on-deis-workflow/ is now published and should help explain this use case. Closing!
