### ISSUE TITLE
Docs: old annotation for ip whitelist doesn't work in V2

### ISSUE THREAD

**Issue by dmcnaught** [deis/workflow#346]
Using labels in whitelist annotation not supported in deis workflow - need to update docs to reflect that.

https://github.com/deis/workflow/blob/master/src/managing-workflow/security-considerations.md#ip-whitelist

```bash
$ kubectl --namespace=deis annotate service deis-controller router.deis.io/whitelist="10.0.1.0/24:office_intranet,121.212.121.212:dev_jenkins"

And the same applies to applications. For example, to apply a whitelist to an application named example:

$ kubectl --namespace=example annotate service example-web router.deis.io/whitelist="10.0.1.0/24:office_intranet,121.212.121.212:dev_jenkins"
```

Need to remove the `:office_intranet` and `:dev_jenkins`
per @krancour the labels aren't currently supported.
Creating PR to fix now.

**Comment by krancour** [comment]
More background... I believe this was copied from v1.x docs without the discrepancy in support for these labels having been noticed.

> Need to remove the `:office_intranet` and `:dev_jenkins`

Alternatively, we can add support for the labels, but unless you are somehow willing to tackle that right now, I think #347 is just what the doctor ordered since it will at least restore the accuracy of the docs as a reflection of current state.
