### ISSUE TITLE
Does Deis leverage pod possibilities, or 1 pod = 1 container?

### ISSUE THREAD

**Issue by JeanMertz** [deis/workflow#350]
We've deployed Deis to our Kubernetes cluster last week, and it looks and feels really great, awesome work girls and guys 🎉 👍 

Managing and deploying our more simple applications is a breeze with Deis.

Moving a bit up the stack, we've got more complex applications that leverage the concept of a pod to have multiple containers be contained within a single pod.

One example is an application that has:

1. a Ruby Puma server running (with multiple workers)
2. a custom Proxy in front of these workers
3. a Varnish instance in front of the custom proxy

The concept of a pod encapsulates this setup perfectly, and it helps us keep these three components tightly coupled together, all scaling up and down as we scale a single "application deployment".

From what I've seen so far, Deis does not support this setup, is that correct? Are there any plans to support this type of coupled-containers setup, or is the only way to solve this, to register multiple applications at Deis, and have them not be coupled together?

**Comment by krancour** [comment]
@JeanMertz on behalf of the team, thank you for the kind words.

In regard to your question, currently, applications deployed via Workflow assume there is a single container per pod. Obviously, there are many scenarios (such as the one you've outlined) that would be well served by the ability to define "sidecar" containers. I would imagine we will address that eventually, but if so, I also imagine it will be part of a broader initiative to expand beyond support for mere 12factor apps so that we can accommodate today's increasingly common micro-service architectures.

In the meantime, you might consider checking out Deis' _other_ product-- [Helm](https://helm.shi)-- which is much more geared toward using the full power of of k8s to define and deploy more complex applications that utilize micro-service architectures. As I'm sure you've already seen by reaching this point, this is how Workflow itself is deployed, and you can easily take advantage of Helm for your own purposes if it's a better fit for your architecture than Workflow is.

**Comment by JeanMertz** [comment]
Hey @krancour,

Thank you for the quick and thorough explanation. Great product, great support, I suppose 🤗.

I'll be eagerly waiting how Deis handles more complicated application setups, interesting times indeed. Regarding Helm, I definitely saw the project (and indeed worked with it, while deploying Deis), but given the current transition from Helm "Classic" to the Kubernetes-native Helm implementation, we're sitting that one out for now, until it's clear in what direction the new Helm is going.

Thanks again for the feedback 👍

**Comment by pydevops** [comment]
I believe a cool feature would be to support a single pod with multiple container, ideally directly from docker-compose.yml. This is where most developers describe docker containers, volume, networking etc. This would automate the work to translate from docker-compose.xml to kubernetes manifest. Exactly what deis workflow could empower the developer.
