### ISSUE TITLE
add new url to interact with deis/builder

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#351]
*Request:*

`GET /v2/hooks/public_key/{ssh_public_key}`

(where ssh_public_key is the SSH public key as received by the builder in Base64)

*Response:*
```
{
  "username": "john.doe",
  "fingerprint": "",
  "apps": [
    "demo"
  ]
}
```

*Where:*
- `fingerprint` is the stored value in `api_key`
- `repositories` an array that contains all the apps where the user can run `git push`

*Return codes:*
- 200 if the key is valid with the response
- 404 if the key is not a valid one

**Comment by helgi** [comment]
Why this format oppose to gathering keys via app name / user name (we have those endpoints already).

I get you are wanting to do a "is valid / not valid" kind of API check but can't we do that already if we are pulling down all the keys for the given user?

**Comment by aledbf** [comment]
@helgi the problem with #336 is that during the ssh auth phase there's no such thing as user/repo, just a public key (I tried to use the routes from 336 in https://github.com/deis/builder/pull/148)

**Comment by helgi** [comment]
Ah I was under the impression we had access to that information at the time since we were parsing out the `authorized_keys` (before) and so on. That just grabbed the keys then... hmmm... well okay I will add it in today and perhaps just pull out the other hooks if needed since they seem redundant?

Were you planning on posting the public key as a base64 in the URL? Wouldn't we be better off with a POST or were you going to add the decoded string into the URL for GET?

What were you going to use `repositories` for? I'm inclined to rename it to `apps` since that's what it really is if you are just looking for the app name

**Comment by arschles** [comment]
Apologies, I should have been more on top of things here. @aledbf and I talked about passing the public key as base64 in the URL. I'm ok with renaming `repositories` to `apps` as you said @helgi.

Also, my vote would be to remove the other endpoints.

@helgi @aledbf thoughts?

**Comment by aledbf** [comment]
>  perhaps just pull out the other hooks if needed since they seem redundant?

yes but can be after the merge of 148? :)

> I'm inclined to rename it to apps since that's what it really is if you are just looking for the app name

:+1:

**Comment by helgi** [comment]
base64 in the URL feels odd but it is simple. I may change the `public_key` to `key` but we'll see, otherwise I'll implemented it a discussed and pull out the other code in a separate PR

**Comment by helgi** [comment]
The PR for this is ready. Have a look and see if it fits your needs

**Comment by aledbf** [comment]
@helgi testing

**Comment by helgi** [comment]
If Go has it, use the urlsafe base64 encoding
