### ISSUE TITLE
deis git:remote

### ISSUE THREAD

**Issue by andrewho83** [deis/workflow#441]
I'm setting another user on deis, and after trying `deis git:remote`, it print out:

`Error: exit status 129`

Would be nice to have more verbose logging as to what this error involves.

**Comment by Joshua-Anderson** [comment]
I'm so sorry we didn't get back to you on this! Complete ball drop on my part. In the deis CLI `v2.3.0` I redid much of the `deis git` code, making it much more verbose. I believe this error cropped up when trying to add a git remote when a git remote of the same name already existed.

Please try with deis `v2.3.0` and let me know if it comes up again.

If you open issues with the deis CLI in [deis/workflow-cli](https://github.com/deis/workflow-cli) rather than the general issue tracker here, it's slightly easier for us to track issues with specific components.

Thanks for opening up this issue and sorry again for overlooking it!

**Comment by Joshua-Anderson** [comment]
I'm going to close this in favor of deis/workflow-cli#196, which is in a more specific git repository.
