### ISSUE TITLE
Support blue/green deployments

### ISSUE THREAD

**Issue by F21** [deis/workflow#514]
The docs mentions that deployments uses kubernetes' rolling updates.

It would be nice to support blue/green deployments too:
1. Do not scale down old version and deploy all instances of the new version.
2. Wait for all instances of the new version to come online and perform health checks.
3. If health checks fail, delete new deployment.
4. If health checks pass, switch the router over to the new version and delete the old version.

**Comment by helgi** [comment]
We have considered Blue/Green but since Kubernetes does not natively support it (yet) then it is unlikely that we will attempt to try to construct that around ReplicaSets directly.

Technically with RollingUpdates you can kinda achieve that by setting MaxAvailable to be double the amount of pods you want and MaxUnavailable to 0, however, Kubernetes may do unpredictable things as it would think it was in RollingUpdate mode.

https://github.com/kubernetes/community/wiki/Roadmap:-Deployment is their current roadmap for Deployments

**Comment by F21** [comment]
I was just watching this talk on blue/green deployments on kubernetes: https://youtu.be/-Ci4vd4rh4M?t=28m16s

They have an opensource deployer that manages blue/green deployments on kube: https://bitbucket.org/amdatulabs/amdatu-kubernetes-deployer

Maybe this could be adapted for deis.

**Comment by bacongobbler** [comment]
FYI points 1-3 are done, it's just point 4 that would be the meat and potatoes of this enhancement.

**Comment by F21** [comment]
ref https://github.com/kubernetes/kubernetes/issues/33462 for native blue/green deployments in k8s.

**Comment by bacongobbler** [comment]
let's close this one out and re-open once blue/green deployments are available in k8s, then we can look into adapting it into our workflow.

**Comment by bacongobbler** [comment]
on second thought, let's keep this open in case someone feels the need to work on this. :)

**Comment by Haybu** [comment]
I wonder if there is any update on BG addition to deis workflow ?

**Comment by bacongobbler** [comment]
No updates. If you feel like implementing it, there is documentation from Kubernetes on how they support blue/green deployments. We just need to wire it up and add the knobs.

**Comment by bacongobbler** [comment]
I think we can consider this closed now. Point 4 in the OP has been resolved with `deis healthchecks`.
