### ISSUE TITLE
v2.8.0 helm chart: secrets remain on deletion

### ISSUE THREAD

**Issue by seanknox** [deis/workflow#590]
STR:
- Install via new `helm` charts with v2.8.0: `helm install deis/workflow --version=v2.8.0 --namespace=deis`
- Delete the deployed helm release: `helm delete <release-name>`
- Install again: `helm install deis/workflow --version=v2.8.0 --namespace=deis` 

EXPECTED: 
- workflow is deployed successfully via `helm`

ACTUAL:
```
$ helm install deis/workflow --version=v2.8.0 --namespace=deis  
Fetched deis/workflow to workflow-v2.8.0.tgz
Error: secrets "builder-ssh-private-keys" already exists
$ kubectl get secrets -n deis                                                                        
NAME                       TYPE                                  DATA      AGE
builder-key-auth           Opaque                                1         1h
builder-ssh-private-keys   Opaque                                3         1h
database-creds             Opaque                                2         1h
default-token-lel5j        kubernetes.io/service-account-token   3         1h
deis-workflow-manager      Opaque                                1         1h
django-secret-key          Opaque                                1         1h
logger-redis-creds         Opaque                                1         1h
```

**Comment by kmala** [comment]
we kept few secrets as pre-install hooks because they are needed to be created only once during the install and remain constant during an upgrade(ex. database secret with user and password).
Helm doesn't delete the pre-install hooks upon deletion of the release. Already created an issue against helm to support the feature through a flag https://github.com/kubernetes/helm/issues/1464

**Comment by cmcconnell1** [comment]
Although this might not be the correct method to use, I needed to move forward was stuck in limbo after (thinking that I had completely) deleting my existing workflow.  Deleting the namespace allowed me to move forward and re-install my new workflow (with a custom values.yaml).
```
kubectl delete ns deis
namespace "deis" deleted
```
Is there another preferred method instead of using the above? 
Thanks

**Comment by kmala** [comment]
yes...deleting the workflow will not delete all the components because of how upgrade works and what you had is the correct way. We will be releasing the workflow to be installed with the kubernetes helm(https://github.com/kubernetes/helm) charts which should improve the usability a lot.
