### ISSUE TITLE
How to config "Native Ingress" on minikube or IBM cloud?

### ISSUE THREAD

**Issue by ermaoCode** [deis/workflow#865]
I follow the [guide](https://deis.com/docs/workflow/installing-workflow/experimental-native-ingress/)  and got a problem.
It says that:

> Additionally, we need to point the deis-builder.$host record to the public IP address of the Builder.
> $ kubectl get svc deis-builder --namespace deis
> NAME           CLUSTER-IP     EXTERNAL-IP     PORT(S)          AGE
> deis-builder   10.0.165.140   40.86.182.187   2222:32488/TCP   33m

But, when i use minikube, there is no External ip for the builder. it seems like this:
```
$ kubectl get svc deis-builder --namespace deis
NAME           TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
deis-builder   LoadBalancer   10.0.0.40    <pending>     2222:31972/TCP   4d
```
This question also exist when i use IBM cloud, on which i have to use `bx cs workers < cluster-name >` to get the node ip.

**Comment by bacongobbler** [comment]
For minikube, this is described in the quickstart documentation: https://deis.com/docs/workflow/quickstart/provider/minikube/dns/

Also tacking on here as an FYI that Deis Workflow is no longer maintained. Please [read the announcement](https://deis.com/blog/2017/deis-workflow-final-release/) for more detail. Because of that, I'm going to go ahead and close this issue.

Thanks!

**Comment by ermaoCode** [comment]
OK,  thanks.
