### ISSUE TITLE
Docs and Charts are unreachable

### ISSUE THREAD

**Issue by yuya-takeyama** [deis/workflow#867]
Dear Deis team,

Some URLs in deis.com is unreachable.

* https://deis.com/docs/workflow/
  * It's linked from http://docs.deis.io/en/latest/
* https://charts.deis.com/workflow
  * When I run `helm repo add deis https://charts.deis.com/workflow`, it fails with a message `Error: Looks like "https://charts.deis.com/workflow" is not a valid chart repository or cannot be reached: Get https://charts.deis.com/workflow/index.yaml: dial tcp: lookup charts.deis.com on 127.0.0.11:53: no such host`

I know it's no longer maintained.
So our team are migrating to a new platform right now.

We still need the resources.
Please, please don't break the web easily.

I'll appreciate your kind help.

**Comment by bacongobbler** [comment]
Hey @yuya-takeyama,

We apologize for any inconvenience shutting down deis.com caused. We shared our end of life plans a few months ago, and you can read more about it [here](https://web.archive.org/web/20180626034638/https:/deis.com/blog/2017/deis-workflow-final-release/).

In the meantime, happy to see if we can help you complete your transition to a new platform. I can send you a link to the source code and give you a set of instructions on how to install from source. Would that help?

**Comment by Nodraak** [comment]
Hi @bacongobbler 

Sorry to bother you here, but I don't how to contact someone from Deis otherwise, so I'll use this recent issue.

It is very sad to learn that deis.com has shut down, there was valuable blog posts at deis.com/blog/. Was they migrated somewhere ? I could not find them on web.archive.com

**Comment by idealhack** [comment]
@bacongobbler Hi, Could you post those source code and instructions here? We need to install deis for a legacy app.

**Comment by idealhack** [comment]
For who are still using Deis, use the Hephy fork instead.

**Comment by bacongobbler** [comment]
Source code for the Deis Workflow chart is available [here](https://github.com/deis/workflow/tree/master/charts/workflow), with the corresponding documentation found [here](https://github.com/deis/workflow/tree/master/src). Thanks!

**Comment by dalu** [comment]
Thanks bacongobbler, but what's the story behind all this? The sudden disappearance?
Is there a blog post or something I can read?

**Comment by bacongobbler** [comment]
In terms of the website, the Deis team (including myself) are now part of the Azure team at Microsoft. We were acquired back in early 2017.

Because we were a small team, we decided to focus our efforts on other tools in the Kubernetes ecosystem like [Helm](https://github.com/helm/helm), [Service Catalog](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/) and [Draft](https://github.com/Azure/draft/). We shared our team's plans to shut down our supporting infrastructure (including our CI infrastructure, deis.com and charts.deis.com) on the blog, which has since shut down but can be found [on web.archive.org](https://web.archive.org/web/20180626034638/https:/deis.com/blog/2017/deis-workflow-final-release/).

> [why] the sudden disappearance?

We continued to maintain the project for over a year and a half after announcing we were ending support. We gave existing users a significantly large window of time to consider migrating (or to consider maintaining a fork, as the Hephy team did), as well as *plenty* of warning what was happening throughout the entire process. It certainly wasn't sudden if you ask me 😆 

As for the Hephy fork, it's a fork of Deis Workflow where a group of community members are continuing to move the project forward after deis.com went dark. You can find the project site here: https://web.teamhephy.com/

Let me know if you have further questions.

**Comment by bacongobbler** [comment]
To answer @Nodraak's earlier question

> Was they migrated somewhere ? I could not find them on web.archive.com

I looked into this when we heard the news that were were shutting down. Unfortunately due to licensing agreements with how some of the blog posts were authored, we are unable to re-distribute the site (and with that, the blogs).
